// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcIg51Dk4WRlEG41udyhd9G624sOLWkIQ',
    appId: '1:442641577563:web:6fae3ec52e396c1de3317e',
    messagingSenderId: '442641577563',
    projectId: 'gymapp-43a49',
    authDomain: 'gymapp-43a49.firebaseapp.com',
    storageBucket: 'gymapp-43a49.firebasestorage.app',
    measurementId: 'G-M04PT7MGEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg65jRcYj4wBdRqiMkJtVA_yXIevN9nG4',
    appId: '1:442641577563:android:8c2d6522d40d0a16e3317e',
    messagingSenderId: '442641577563',
    projectId: 'gymapp-43a49',
    storageBucket: 'gymapp-43a49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL7DcZI9qFLJ3OPmKWEqg7dm-bXSmzGEg',
    appId: '1:442641577563:ios:34c2a16a05084fc6e3317e',
    messagingSenderId: '442641577563',
    projectId: 'gymapp-43a49',
    storageBucket: 'gymapp-43a49.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL7DcZI9qFLJ3OPmKWEqg7dm-bXSmzGEg',
    appId: '1:442641577563:ios:34c2a16a05084fc6e3317e',
    messagingSenderId: '442641577563',
    projectId: 'gymapp-43a49',
    storageBucket: 'gymapp-43a49.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcIg51Dk4WRlEG41udyhd9G624sOLWkIQ',
    appId: '1:442641577563:web:026b3ae27122734ae3317e',
    messagingSenderId: '442641577563',
    projectId: 'gymapp-43a49',
    authDomain: 'gymapp-43a49.firebaseapp.com',
    storageBucket: 'gymapp-43a49.firebasestorage.app',
    measurementId: 'G-F8QTRHYMZC',
  );
}
